---
# main task for role execution

- name: configure proxmox vm state
  hosts: localhost
  gather_facts: true
  become: true
  
  tasks:
  
  - name: pve vm state
    include_role:
      name: pve_vm_state

