---
# main tasks for pve_vm_state
- name: Update ProxmoxVE Virtual Machine State
  proxmox_kvm:
    api_user: "{{proxmox_user}}"
    api_password: "{{proxmox_password}}"
    api_host: "{{proxmox_host}}"
    name: "{{item.name}}"
    state: "{{item.state}}"
    force: yes
    proxmox_default_behavior: no_defaults
    validate_certs: no
  loop: "{{vm_guest}}"
  register: results

- name: results
  debug:
    msg: "{{ results }}"
